### ISSUE TITLE
Sponsor image is hard to read on dark themes

### ISSUE THREAD

**Issue by arielj** [fastruby/points#104]
**Branch/Commit:**

Main branch

**Expected behavior:**

The sponsor image at the bottom of the readme should be readable in both light and dark themes.

**Actual behavior:**

The sponsor image has transparent background and black text and it's not readable on the dark theme.

**Screenshots and Videos**

![image](https://user-images.githubusercontent.com/188464/137509569-6f8035a5-960f-44b2-8a8c-c38c68002018.png)

Check dotenv_validator for reference:

![image](https://user-images.githubusercontent.com/188464/137509613-c1fc50d6-f55e-49a2-a525-16bbb984b4e3.png)
(though I think this one is too big and pixelated, maybe a middle ground with the previous size but clear background is better)

**I will abide by the [code of conduct](https://github.com/fastruby/points/blob/main/CODE_OF_CONDUCT.md)**

**Comment by lubc** [comment]
Fixed in https://github.com/fastruby/points/commit/3a8251377b8f7913b8346a4c9348e5bf761dcb77
