### ISSUE TITLE
Add `copy to clipboard` buttons next to stories to copy the url for easy sharing

### ISSUE THREAD

**Issue by arielj** [fastruby/points#113]
**Branch/Commit:**

Main branch.

**Describe the feature:**

As a user, I want to be able to quickly copy a url to the clipboard to share it.

**Problem:**

There are many places where links for stories are not visible (like when you are estimating a story using a modal or you are on 
a mobile device) or from the list of stories (you have to right click -> copy link).

**Mockups:**

Having a small icon next to story names in some places can help solve this problem.

maybe here:
![image](https://user-images.githubusercontent.com/188464/139133220-2d3ff6be-ed1a-4e84-9132-2d4156365e86.png)

and here:
![image](https://user-images.githubusercontent.com/188464/139133301-af5d52ba-c128-4457-bf47-090f0a1aa3c9.png)

I'm not sure exactly where is the best place, but once we have the helper/widget we can put it in places as we need.

**I will abide by the [code of conduct](https://github.com/fastruby/points/blob/main/CODE_OF_CONDUCT.md)**

**Comment by mateusdeap** [comment]
I like this one. I think we can try and do what JIRA does. It's pretty handy
