### ISSUE TITLE
Docker environment is still broke

### ISSUE THREAD

**Issue by bronzdoc** [fastruby/points#117]
> NOTE I will add more info later :shipit: 

When I ran `$ docker-compose up` the `web-next` service is overwriting the `web` in someway so the web service is not available

**I will abide by the [code of conduct](https://github.com/fastruby/points/blob/main/CODE_OF_CONDUCT.md)**

**Comment by kindoflew** [comment]
@bronzdoc, info please :shipit:

**Comment by bronzdoc** [comment]
@kindoflew try to `docker-compose up` and try to access the app locally in port `3000`
