### ISSUE TITLE
Improve what happens when linking to a story that does not exist anymore

### ISSUE THREAD

**Issue by arielj** [fastruby/points#126]
https://ombulabs.atlassian.net/browse/DT-260

**Branch/Commit:**

Main branch

**Describe the feature:**

Currently, if you link to a story that doesn't exist, it shows the generic rails error page. We could handle the missing story by redirecting back to the project's show action (or the projects' index if project is missing too) with a flash message like `The story could not be found` or something like that.

**Problem:**

Currently, linking to a story that doesn't exist shows a generic rails error, and it's not clear for the user what that error means.

**I will abide by the [code of conduct](https://github.com/fastruby/points/blob/main/CODE_OF_CONDUCT.md)**

**Comment by etagwerker** [comment]
@arielj @torresga @rishijain I don't agree with this feature. 

Showing a 404 page for a page/story that no longer exists seems reasonable. 

If we don't want this to happen, we could consider using "soft deletion" for stories.

**Comment by etagwerker** [comment]
Closing this for now. Not a priority at the moment.
