### ISSUE TITLE
Add "live estimation" capability

### ISSUE THREAD

**Issue by ABizzinotto** [fastruby/points#14]
https://ombulabs.atlassian.net/browse/DT-265

Points is great for asynchronous estimates. But in some situations we might have a need for a "live estimation". It would be good to have that functionality in Points too.

We would need to be able to:

- Choose a scale (Fibonacci or T-Shirt sizing)
- Add the stories
- Add the "players" (team members that will be estimating using the planning poker activity)
- Have an option to start the estimation process, at which point all players would see the story and the available estimation options to pick one
- Show the result and average once all players have estimated a story and move to the next story
- Finish estimation and generate a report 
- Ability to export the report in CSV format

**Comment by bronzdoc** [comment]
@ABizzinotto Is there a product that we can see that does this so we can have it as a reference?

**Comment by ABizzinotto** [comment]
@bronzdoc yes. This is one that I like (although I hadn't used it in a while): https://www.planitpoker.com/

**Comment by fbuys** [comment]
Not part of our new points vision.
