### ISSUE TITLE
Sub-projects shouldn't allow being archived individually

### ISSUE THREAD

**Issue by arielj** [fastruby/points#152]
**Branch/Commit:**

Main branch

**Expected behavior:**

As a user, I shouldn't see the option to archive a sub-project since we don't really handle archived sub-projects in a different way.

**Actual behavior:**

There's a button to `archive` a sub-project, but it's always shown in its parent and is useless.

**I will abide by the [code of conduct](https://github.com/fastruby/points/blob/main/CODE_OF_CONDUCT.md)**

**Comment by rishijain** [comment]
So what I understand is this

Expected behaviour:
Sub projects should not see the option to archive

Actual Behaviour:
Sub projects have an option to archive the sub project. This option should only show up for parent project.

Is that the right understanding @arielj  ?
