### ISSUE TITLE
Sum of points not accurate in some cases

### ISSUE THREAD

**Issue by geetfun** [fastruby/points#159]
**Branch/Commit:**

`main` branch

**Expected behavior:**

The sum of all visible and non-deleted point tasks should be accurate.

**Actual behavior:**

Copy and pasting all the rows into a spreadsheet software and summing the rows yielded a different number than the one that is displayed.

**Steps to reproduce:**

On an internal roadmap project, it was noticed that there was a large discrepancy between the two estimators lower and upper sums

I do not have access to the underlying data, and so I cannot provide additional information.

We suspect the app may be summing up something that it shouldn't, such as:
- Previously deleted points/tasks (?)

**Logs**

Please see internally running app for details.

**I will abide by the [code of conduct](https://github.com/fastruby/points/blob/main/CODE_OF_CONDUCT.md)**

**Comment by geetfun** [comment]
I am not sure if this issue is addressed, but have added it in here in case it hasn't as it could result in inaccurate estimates for real-world work.

Feel free to close this issue if this has already been fixed.

cc @arielj @neutrino

**Comment by arielj** [comment]
There's already an issue https://github.com/fastruby/points/issues/141
