### ISSUE TITLE
Add support for subprojects

### ISSUE THREAD

**Issue by arielj** [fastruby/points#16]
When we have to do a big upgrade involving different stages and versions jumps, it would be nice to have each thing as a project and one project containing all.

For example: let's say we want to upgrade an app from rails 3.0 to rails 5.0, but also do some big changes in the middle like replacing a gem with an alternative version that should be handled outside the usual upgrade project.

We would have multiple projects:
- Rails 3.0 to 3.1
- Rails 3.1 to 3.2
- Ruby 1.9.3 to 2.3
- Replace X gem with Y replacement
- Rails 3.2 to 4.0
- Rails 4.1 to 4.2
- Rails 4.2 to 5.0

And then a `parent` project to group the rest.

That way, each stage/story of a project can be estimated as a unit and then the parent project can generate the report.

Currently, adding all those projects makes the index full of similar entries and having all the stories into one single project makes it hard to organize them and it can't show the estimation for each separately.

**Comment by rdormer** [comment]
@bronzdoc @arielj so I'm thinking the best way to go about this would be to introduce some type of higher level parent object that can own more than one project.  Then when you create a project, by default you're creating the higher level object with a single child project, and that can be handled in the UI as a special case.  If you create more projects for that parent object, then we'd need to make UI changes to accomodate showing the projects specific to that parent.

Does the basic approach seem sound?  I think it'll be a lot clearer and easier than trying to have a project that `has_many` of itself....

**Comment by arielj** [comment]
While writing this issue I imagined something like:

project belongs_to parent, class_name: 'Project'
project has_name projects

Then in the index we do something like `@projects = Project.where(parent_id: nil)` to list only the projects that are not sub projects. That way we don't need to create higher level projects for the projects we already have in the index, and also we don't need to change anything for the Story model (if we have 2 different kinds of project we would need to make the Story > project some polymorphic association).

Then in the show action, if the project has subprojects we can list them (and then maybe we can have a list of stories for this parent project too), something like:

```
This Super Large Project

Subprojects:
- part 1
- part 2

Stories:
- some story for the parent
- another story for the parent

actions: add story, add subproject, edit, etc
```

If that makes sense I prefer that instead of adding another class

**Comment by rdormer** [comment]
@bronzdoc @arielj do you think it makes sense to include reporting in this feature?  I'm inclined to push that off to another separate story.  At the very least, we need to define how we want to handle compiling and exporting reports for projects with subprojects.

**Comment by arielj** [comment]
@rdormer I think it's ok to do the reporting in a different story too. I understand that, since subprojects are simply projects, it should be easy to create the report for each subproject one by one. Eventually it would be nice to have an action on the parent project to export the whole report but probably better outside this.
