### ISSUE TITLE
Search feature for all stories across projects

### ISSUE THREAD

**Issue by etagwerker** [fastruby/points#199]
https://ombulabs.atlassian.net/browse/DT-252

**Before we start...:**

- [x] I checked the documentation and didn't find this feature
- [x] I checked to make sure that this feature has not already been requested

**Branch/Commit:**

main branch

**Describe the feature:**

Please include a detailed description of the feature you are requesting and any detail on it’s expected behavior.

> **As an estimator**
> **I search for a story (by title and/or description)**
> **And then I see a bunch of stories across projects**

**Problem:**

Please include a detailed description of the problem this feature would solve.

> **As an estimator**
> **I want to see past stories**
> **So that I can understand previous estimations of similar stories**

**Challenges:**

As part of our blind estimation process, we probably don't want to display estimations for recent stories (or the project that I'm currently working on) so that we can keep estimators opinion unbiased.

**I will abide by the [code of conduct](https://github.com/fastruby/points/blob/main/CODE_OF_CONDUCT.md)**

**Comment by mcelaney** [comment]
Hey @etagwerker 

I'm proposing the `pg_search` gem for this - gives us full text search on title and description without a ton of fuss.  PR has the basic setup although I'm still trying to work out how to get turbolinks to be reasonable.

Did you have any thoughts on what to include in the search results?

<img width="1189" alt="Screen Shot 2022-03-11 at 8 23 10 PM" src="https://user-images.githubusercontent.com/607860/157998621-3bc12ee4-759f-469b-8d65-2054c8f1f280.png">

**Comment by etagwerker** [comment]
Closing this for now, as search is now available for admins through the admin panel.
