### ISSUE TITLE
Flaky sort sub projects spec

### ISSUE THREAD

**Issue by arielj** [fastruby/points#204]
**Branch/Commit:**

Main branch

**Expected behavior:**

Specs should not be flaky.

**Actual behavior:**

The spec to sort sub project uses the drag_to method that is not too stable, causing failures too often on CI.

**Steps to reproduce:**

Check CI for the latest PRs

**I will abide by the [code of conduct](https://github.com/fastruby/points/blob/main/CODE_OF_CONDUCT.md)**

**Comment by etagwerker** [comment]
@arielj This just happened in this build: https://github.com/fastruby/points/runs/5015209263?check_suite_focus=true
