### ISSUE TITLE
[Feature Request] Make the `Add Story` button always visible

### ISSUE THREAD

**Issue by arielj** [fastruby/points#21]
Currently, when adding stories, for every story we add we have to scroll all the way down. It gets longer every time.

It would be nice to have the `Add Story` action always visible, following the scroll for easy access (either as a floating call to action or a button in a fixed position inside the content like a sticky header).

Some examples of what I mean:
![image](https://user-images.githubusercontent.com/188464/107790976-2adf4600-6d32-11eb-8515-742619259d10.png)
iOS version shows the main action at the top bar, Android shows a floating button at the bottom right corner

**Comment by buys-fran** [comment]
Can I claim this one please?

**Comment by arielj** [comment]
> Can I claim this one please?

@buys-fran I assigned you to the issue 👍

**Comment by bronzdoc** [comment]
closed by https://github.com/fastruby/points/pull/31
