### ISSUE TITLE
Update ruby version from 3.0 to 3.1

### ISSUE THREAD

**Issue by rishijain** [fastruby/points#249]
**IMPORTANT: please make sure you ask yourself all intro questions and fill all sections of the template.**

**Before we start...:**

- [ :heavy_check_mark: ] I checked the documentation and didn't find this feature
- [ :heavy_check_mark: ] I checked to make sure that this feature has not already been requested

**Describe the feature:**

There is already a PR to upgrade the app to Rails 7.0. Here is that PR: https://github.com/fastruby/points/pull/248
We need to upgrade from ruby 3.0 to 3.1.

It has been attempted in the past in this PR although it also included upgrade to rails 7.0, so use this PR only to reference changes or spec failures, but don't build on top of this pr https://github.com/fastruby/points/pull/190

**Problem:**

Update ruby version from 3.0 to 3.1

https://ombulabs.atlassian.net/browse/DT-222

**Comment by fbuys** [comment]
https://github.com/fastruby/points/pull/269
