### ISSUE TITLE
Populate Real Scores

### ISSUE THREAD

**Issue by JuanVqz** [fastruby/points#255]
**IMPORTANT: please make sure you ask yourself all intro questions and fill all sections of the template.**

**Before we start...:**

- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [ ] I'm reporting the issue to the correct repository (for multi-repository projects)

**Branch/Commit:**

Inform what branch/commit of Points you are using.
**main**

**Expected behavior:**

Please include a detailed description of the behavior you were expecting when you encountered this issue.

**Actual behavior:**

If you add real scores per batch when editing real scores again you will miss the previews real scores that you entered

**Steps to reproduce:**

1. Log In
2. Go to a project that has stories
3. Go to the report
4. Click on Populate Real Stories
5. Enter a few real stories and save it
6. Then return to the same Real Stories form
7. You won't see the previous Real Stories you entered.

**Context and environment:**

Provide any relevant information about your setup (Customize the list accordingly based on what info is relevant to this project)

1. from Main branch
2. Manjaro Linux
9. Chromium
10. Version 101.0.4951.64 (Official Build) Manjaro Linux (64-bit)
11. PC 

**Screenshots and Videos**

![Peek 2022-05-17 11-02](https://user-images.githubusercontent.com/7331511/169089045-ab508f7f-e072-4f18-9a65-d0d7659a99dc.gif)

**Logs**

Include relevant log snippets or files here.

**I will abide by the [code of conduct](https://github.com/fastruby/points/blob/main/CODE_OF_CONDUCT.md)**

**Comment by JuanVqz** [comment]
I'm open to add more information if needed, :wave:

**Comment by arielj** [comment]
This seems to have been fixed by https://github.com/fastruby/points/pull/284
