### ISSUE TITLE
Prevent accidental deletion of projects like Github does

### ISSUE THREAD

**Issue by arielj** [fastruby/points#258]
**Branch/Commit:**

Main branch.

**Describe the feature:**

It would be nice for points to require the user to type the name of the project they want to delete instead of just asking to confirm/cancel, like Github does.

**Problem:**

Currently, the confirmation dialog is really generic and somebody can miss the text o even miss the cancel button and confirm deletion of a project.

Enforcing that the user types the project name is a good an simple measure.

**Mockups:**

This is what github shows when trying to delete a repository:
![image](https://user-images.githubusercontent.com/188464/171431360-83d243a2-c7f3-4419-8cb7-4706c1a603b0.png)

**I will abide by the [code of conduct](https://github.com/fastruby/points/blob/main/CODE_OF_CONDUCT.md)**

**Comment by ABizzinotto** [comment]
As we work towards leveraging Points data more and more, preventing accidential deletion helps prevent downstream failures. Raising the priority.
