### ISSUE TITLE
The Create button gets odd when estimating

### ISSUE THREAD

**Issue by JuanVqz** [fastruby/points#266]
While working on DT-372 I found this error.

- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

**Expected behavior:**

Be able to create an estimation.

**Actual behavior:**

The button to save estimations gets odd.

![error-points](https://user-images.githubusercontent.com/7331511/175760592-d4355c0d-062f-4a8e-889d-568c78b499cd.gif)

**I will abide by the [code of conduct](https://github.com/fastruby/points/blob/main/CODE_OF_CONDUCT.md)**

**Comment by arielj** [comment]
Weird, I remember there was an issue for this already, not sure why it was marked as completed at some point https://github.com/fastruby/points/issues/115
