### ISSUE TITLE
Create the ability to copy a project or stories into another project

### ISSUE THREAD

**Issue by FionaDL** [fastruby/points#33]
As a user I would like to  be able to create a project where I can choose a set of stories copied from another project. This way we could have sample projects or templates to build off when we begin a new project.  This would save a lot  of time when sets of stories  are used over and over.

**Comment by buys-fran** [comment]
I'll take a look at this one

**Comment by buys-fran** [comment]
@FionaDL what do you think of the ability to duplicate a project?
Or do you see a problem with this approach?
Also, would you expect the estimates to be copied as well, or only the stories?

**Comment by FionaDL** [comment]
@buys-fran the ability to duplicate a project would be great! I don't think estimates should be copied, because that should depend on the developer.
