### ISSUE TITLE
UI: It is not clear for the user that the CSV import/export title is clickable

### ISSUE THREAD

**Issue by delucas** [fastruby/points#35]
**IMPORTANT: please make sure you ask yourself all intro questions and fill all sections of the template.**

**Before we start...:**

- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed
- [X] I'm reporting the issue to the correct repository (for multi-repository projects)

**Branch/Commit:**

main

**Expected behavior:**

All clickable elements in an interface should present clear clues for users.

**Actual behavior:**

The **CSV Import/Export** sign that shows some additional fields, does not show any visual clue

**Steps to reproduce:**

How do I achieve this behavior? Use the following format to provide a step-by-step guide:

1. Go to any project's page
2. There is the sign without clues (see pics below)

**Context and environment:**

Provide any relevant information about your setup (Customize the list accordingly based on what info is relevant to this project)

1. Version of the software the issue is being opened for. Currently deployed version
2. Operating System N/A
3. Operating System version N/A
4. Browser: Firefox
5. Browser version: 88
6. Device N/A

_Delete any information that is not relevant._

If you are unable to reproduce the bug, add the **Non-Reproducible** tag and describe the steps you followed leading to the bug to the best of your recollection.

**Screenshots and Videos**

Before clicking:
![Selection_659](https://user-images.githubusercontent.com/684051/116597132-9b424000-a8fb-11eb-9781-8e0a9865f36e.png)

After clicking:
![Selection_660](https://user-images.githubusercontent.com/684051/116597151-9ed5c700-a8fb-11eb-825b-3a210884d93b.png)

**Comment by buys-fran** [comment]
I will address this issue within the next week or so
