### ISSUE TITLE
[BUG] Can't Log in (intermittently) 

### ISSUE THREAD

**Issue by tiagocasanovapt** [fastruby/points#47]
**IMPORTANT: please make sure you ask yourself all intro questions and fill all sections of the template.**

**Before we start...:**

- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

**Branch/Commit:**

main

**Expected behavior:**

I should be able to Log In with Github.

**Actual behavior:**

Log in fails with a 500 error.

**Steps to reproduce:** [**Non-Reproducible intermittently**]

How do I achieve this behavior? Use the following format to provide a step-by-step guide: 

(usually after full shutdown/restart, or after quitting the browser)
1. Step 1: Open http://points.ombulabs.com/users/sign_in
2. Step 2: Click "Sign in With Github"

**Context and environment:**

Provide any relevant information about your setup (Customize the list accordingly based on what info is relevant to this project)

1. Currently deployed version
2. macOS Big Sur
3. 11.4 (20F71)
4. Brave Browser
5. Version 1.25.68 Chromium: 91.0.4472.77 (Official Build) (x86_64)

**Screenshots and Videos**

<img width="450" alt="Screenshot 2021-06-07 at 15 46 33" src="https://user-images.githubusercontent.com/2427867/121037686-8f258a00-c7a7-11eb-9658-31cd32aadb5a.png">

[Screen Recording 2021-06-07 at 15.21.02.zip](https://github.com/fastruby/points/files/6609932/Screen.Recording.2021-06-07.at.15.21.02.zip)

**Logs**

[requests_as_fetch.txt](https://github.com/fastruby/points/files/6609934/requests_as_fetch.txt)
[requests_as_curl.txt](https://github.com/fastruby/points/files/6609935/requests_as_curl.txt)

All requests are included, since they're all redirects, responses are empty until the 500 error, which is the last request.

**I will abide by the [code of conduct] (CODE_OF_CONDUCT.md)**

**Comment by buys-fran** [comment]
I tested this and it works in chrome.
@torresga tried it in Firefox and Safari, and it works as expected in both browsers.

I believe @arielj fixed it when he updated the OAuth config in github.
@arielj can we close this issue?
@tiagocasanovapt are you able to replicate this now?

**Comment by tiagocasanovapt** [comment]
Indeed, I didn't have any error today. I can always re-open the issue if needed 👍
