### ISSUE TITLE
Specify the Ruby version that should be used

### ISSUE THREAD

**Issue by arielj** [fastruby/points#60]
**Branch/Commit:**

Main branch

**Describe the feature:**

As a user developer, I want to see which Ruby version I should use to run the app.

**Problem:**

Currently we have a mix of versions:
- CI config is using 2.6.3
- the `.ruby-version.sample` files shows 2.4.1
- the Gemfile has no definition of the Ruby version (Heroku uses this)
- our deployment in heroku is using 2.5.3

Since we are already using 2.6.3 on CI, I think it would be a good idea to set that version to use since it's the one that's always tested (though maybe somebody has another suggestion, maybe test the app in many ruby versions on CI?)

**I will abide by the [code of conduct](CODE_OF_CONDUCT.md)**

**Comment by mateusdeap** [comment]
I can commit this change. Also, I believe we should maybe alter the `bin/setup` script to first create the `.ruby-version` (and, in my case, I also want to add  a `.tool-versions` for myself and the possible future asdf users out there) and then install bundler. Should I create a separate issue for that?

**Comment by bronzdoc** [comment]
We should ignore the `.ruby-version` in git and define the ruby version in the Gemfile
@mateusdeap what is `.tool-versions` ?

**Comment by mateusdeap** [comment]
Aaah, I see, I'll modify the PR then.

`.tool-versions` is just how `asdf` manages versions to basically... well, anything, really. Ruby, node, stuff like that. Usually it's for languages and runtimes

**Comment by mateusdeap** [comment]
I'll also add the ruby version to the Gemfile
