### ISSUE TITLE
Improve projects-subprojects navigation

### ISSUE THREAD

**Issue by arielj** [fastruby/points#75]
**Branch/Commit:**

Main

**Describe the feature:**

It would come handy to have a sidebar with the structure of the project like:

Some Upgrade Project:
- Rails 3.2 to 4.0
- Rails 4.0 to 4.1
- Rails 4.1 to 4.2

That way we can move between the different subprojects quickly

**Problem:**

Currently it's too hard to navigate between the main project and the subprojects, having to go back and forth to the index page.

**I will abide by the [code of conduct](CODE_OF_CONDUCT.md)**

**Comment by neutrino** [comment]
@arielj : I am thinking about displaying the sub-projects in the project show page along with the stories for the project. So, instead of visiting the home page to navigate to another sub-project, user can access it from the project show page.

**Comment by arielj** [comment]
This was already merged, closing.
