### ISSUE TITLE
Total estimates row is not updated after adding an estimate with ajax

### ISSUE THREAD

**Issue by arielj** [fastruby/points#77]
**Branch/Commit:**

Main

**Expected behavior:**

After adding/editing an estimate, the line `Total estimates` after the table should show the current state.

**Actual behavior:**

The `Total estimates` are not updated until we refresh the page.

**Steps to reproduce:**

Pick any project and add an estimate using the modal / ajax. The total estimates won't change. Refresh the page. The total will be updated.

**I will abide by the [code of conduct] (CODE_OF_CONDUCT.md)**

**Comment by bronzdoc** [comment]
closed by https://github.com/fastruby/points/pull/85
