### ISSUE TITLE
Ordering doesn't work consistently

### ISSUE THREAD

**Issue by arielj** [fastruby/points#9]
Sometimes, after dragging a story by mistake (but leaving it in the same spot where it was) or editing stories moves them to different positions.

I couldn't find a concrete step-by-step way to reproduce it.

I think the issue is that the `sort` action increases positions by 1 and new stories my have a lower position

**Comment by rdormer** [comment]
I strongly suspect this is actually an issue on the front end.  The backend just sorts stories according to the order that is submitted to it.  Whatever order stories are sent to it for for sorting, that is the order they'll end up in.  That would also explain the flakiness (I haven't been able to reproduce it either) and the fact that it occurs when a story is dragged by mistake.

**Comment by bronzdoc** [comment]
Could not reproduce, if some fins a way to reproduce this to know what to fix we will re open, thanks

**Comment by arielj** [comment]
@bronzdoc I found a way to reproduce this. I understand the issue is that stories are created with no position value, so until you go and arrange then in some order, the stories that don't have a position doesn't respect an order.

You can do this:
1 - create story `Story 1`
2 - create story `Story 2` (you have story 1 and then story 2 in the index)
3 - edit `Story 1`'s descritption
4 - `Story 1` is moved to the bottom

5 - move `Story 1` to the top (now both stories have a `position` value)
6 - create `Story 3`
7 - create `Story 4` (you should have 1, 2, 3, 4 in that order, but 3 and 4 has no position value)
8 - edit `Story 3`'s description
9 - now order is 1, 2, 4, 3

We need to add a position when creating stories.

**Comment by bronzdoc** [comment]
Thanks for the steps to reproduce @arielj! will try them later today
