### ISSUE TITLE
`My Projects` title is confusing

### ISSUE THREAD

**Issue by arielj** [fastruby/points#96]
**Branch/Commit:**

Main branch

**Expected behavior:**

I want to see a clear title in the projects' index. Maybe `Projects` or even no title at all?

**Actual behavior:**

The title in the projects index is `My Projects` and it gives the impression that the projects a user see there are scoped to be only that user's projects, but we don't have that concept. This is the list of all projects.

**Screenshots and Videos**

![image](https://user-images.githubusercontent.com/188464/137348155-1bd77383-c301-4cc6-80ac-8752fbe5866f.png)

**I will abide by the [code of conduct](https://github.com/fastruby/points/blob/main/CODE_OF_CONDUCT.md)**

**Comment by kindoflew** [comment]
Closed via #130.
